### ISSUE TITLE
发送图片出现网络问题

### ISSUE THREAD

**Issue by Sakurabluer** [CikeyQi/nai-plugin#1]
你好，我在配置这config的时候只看见了写入nai，token配置的地方，我想对接nai3，但填写好token以后报错
![image](https://github.com/CikeyQi/nai-plugin/assets/102283052/cdb6089f-b038-4c15-a53d-e28e470541b7)
![{$RBIZJN }D(D{UYZ{1@S3M](https://github.com/CikeyQi/nai-plugin/assets/102283052/878b31d1-0274-4b33-adf7-e7dc78c406f1)
请问我是少填了什么东西嘛，我也看到了类似图片返回的样子
![Uploading 39F}_}C%]J2R]$PQ%0HM$5N.png…]()

**Comment by Sakurabluer** [comment]
![Uploading 39F}_}C%]J2R]$PQ%0HM$5N.png…]()
抱歉上传错了一张

**Comment by Sakurabluer** [comment]
> ![Uploading 39F}_}C%]J2R]$PQ%0HM$5N.png…]() 抱歉上传错了一张

![Uploading 39F}_}C%]J2R]$PQ%0HM$5N.png…]()

**Comment by CikeyQi** [comment]
现在看您反馈的日志来说，程序运行正常且正常绘制了图片并存入了本地，但出现了网络异常，我们仔细检查代码后发现这不属于我们代码逻辑的报错，我们希望能在您的服务器上实机调试，以便找出问题，如果方便请与我联系QQ：3146312184
