### ISSUE TITLE
Axios Error: connect ECONNREFUSED 127.0.0.1:7890

### ISSUE THREAD

**Issue by caozhaofeng** [CikeyQi/nai-plugin#10]
你好，这边突然出现了网络问题Axios Error: connect ECONNREFUSED 127.0.0.1:7890
请问该如何解决
![)5W8Z @DB(GAY5JTY$KZYXE](https://github.com/CikeyQi/nai-plugin/assets/136556424/595bab77-ece7-4873-b32e-e3859f6f016b)

**Comment by CikeyQi** [comment]
你代理寄了

**Comment by caozhaofeng** [comment]
好奇怪，我卸载重装后，又有用了
