### ISSUE TITLE
新功能氛围转移

### ISSUE THREAD

**Issue by Kiana1314** [CikeyQi/nai-plugin#12]
佬  新出的功能会更新吗
![{49E4D401-6EFE-41d8-9BF8-79A6839EF347}](https://github.com/CikeyQi/nai-plugin/assets/107671434/2deecbae-a8de-4fa7-bac3-cfe171642eb2)

**Comment by CikeyQi** [comment]
如果交互不麻烦的话会考虑，明天起床看看实际交互情况再决定

**Comment by Kiana1314** [comment]
佬tql
