### ISSUE TITLE
trss崽的TG适配器识别不到以图画图的图片

### ISSUE THREAD

**Issue by Kiana1314** [CikeyQi/nai-plugin#13]
![image](https://github.com/CikeyQi/nai-plugin/assets/107671434/ffc35846-7e2c-41a2-aa49-37c4dc9f8aab)
[TRSSYz][17:31:17.651][INFO] [tg_6526396568] 群消息：[[忽悠verse]AI深度学习中心-novelai3(tg_-1002067307395), 迷失老司机-BigGay_123(tg_960069913)]
[TRSSYz][17:31:28.904][INFO] [tg_6526396568] 群消息：[[忽悠verse]AI深度学习中心-novelai3(tg_-1002067307395), 迷失老司机-BigGay_123(tg_960069913)] /以图画图
[TRSSYz][17:31:28.961][INFO] [nai-以图画图][img2img][[忽悠verse]AI深度学习中心-novelai3(tg_-1002067307395), 迷失老司机-BigGay_123(tg_960069913)] /以图画图
[TRSSYz][17:31:28.962][INFO] [tg_6526396568] 发送文本：[-1002067307395] 请将图片连同指令一起发送
[TRSSYz][17:31:30.951][MARK] [nai-以图画图][img2img] #以图画图 处理完成 1987ms

**Comment by CikeyQi** [comment]
应该给给telegram适配器提issue
