### ISSUE TITLE
画图报错

### ISSUE THREAD

**Issue by fengruo11123** [CikeyQi/nai-plugin#14]
![8%XM_KX(_IGI18~NXT{P~%K](https://github.com/CikeyQi/nai-plugin/assets/162260068/b63bc84e-27db-45ee-a7f4-c2e7ed8009a7)
梯子开着，依赖也没有问题，前几天还正常 今天就一画就寄了 也一直拉取的是最新的，好像指向的是队列的js有未定义的值

**Comment by CikeyQi** [comment]
启动时检查插件是否正常加载Token，根据报错进行处理

**Comment by fengruo11123** [comment]
> 启动时检查插件是否正常加载Token，根据报错进行处理

好的 明天重启下试试

**Comment by ryq1212** [comment]
> 启动时检查插件是否正常加载Token，根据报错进行处理

我的也是这个报错，但账户信息可以查到，说明Token应该没问题
![微信截图_20240306164700](https://github.com/CikeyQi/nai-plugin/assets/48342188/fa84f95a-b3ec-4057-845e-682b3744e2a6)
