### ISSUE TITLE
之前可以使用，突然变成402，重装机器人，重装插件也不行

### ISSUE THREAD

**Issue by Coisini-H** [CikeyQi/nai-plugin#19]

**Comment by CikeyQi** [comment]
"Request failed with status code 402" 表示一个网络请求失败了，因为服务器返回了一个402状态码。在HTTP协议中，状态码402通常与支付相关，其完整含义是"Payment Required"（需要支付）。这意味着为了进行这次请求或者访问这个资源，服务器端要求客户端完成支付。也就是说，要想使用这项服务或获取这些数据，可能需要先支付一定的费用。

**Comment by CikeyQi** [comment]
初步判断为账号问题，希望能提供账号 Token 进一步测试

**Comment by Coisini-H** [comment]
> 初步判断为账号问题，希望能提供账号 Token 进一步测试

抱歉，麻烦了，真是账户的Token出问题了，账户的Token被朋友改了，没告诉我，抱歉，麻烦你了
