### ISSUE TITLE
一直报这个错误

### ISSUE THREAD

**Issue by Yanm9981** [CikeyQi/nai-plugin#2]
![1701478179691](https://github.com/CikeyQi/nai-plugin/assets/93921255/f5ed4e9c-8a86-4f39-95ea-7166dc6c8fa5)

**Comment by CikeyQi** [comment]
已经更新拦截错误方法，建议更新后查看错误问题

**Comment by luwujie9038** [comment]
> ![图片](https://private-user-images.githubusercontent.com/93921255/287564701-325666ec-67db-4352-8656-d7d58cf385ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NTg0MjksIm5iZiI6MTcwMTY1ODEyOSwicGF0aCI6Ii85MzkyMTI1NS8yODc1NjQ3MDEtMzI1NjY2ZWMtNjdkYi00MzUyLTg2NTYtZDdkNThjZjM4NWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDAyNDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNmQ0OGI4NTkzMDlhYTZkOTU5ZjkzMjViMGM5M2Y3MDQ5NWRlZjY4MTYwM2Q2Y2RlYzExYzEwN2RkZDcxYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fYkF2kHSHurW9EDQKA76mtBWSfkAOwS6kPegCGSbnhs)

把配置文件的代理打开

**Comment by YM-G9981** [comment]
![图片](https://github.com/CikeyQi/nai-plugin/assets/93921255/1aa7d6c3-edb1-4420-9df2-23e3aed9594d)
![图片](https://github.com/CikeyQi/nai-plugin/assets/93921255/85c4d470-d903-4353-baa4-431ffd6791f9)

**Comment by luwujie9038** [comment]
> 我发现我账号没有token，那没事了

6
