### ISSUE TITLE
Image2Image似乎和官网的不太一样？

### ISSUE THREAD

**Issue by luluxiaoyu** [CikeyQi/nai-plugin#20]
这是插件出图的metadata（机器人有回报[已上传参考图片]）：
![image](https://github.com/CikeyQi/nai-plugin/assets/58876608/a942e328-3e5d-4111-819d-586cf29ca4eb)
这是官网出图的metadata：
![image](https://github.com/CikeyQi/nai-plugin/assets/58876608/11851c87-f6ce-4804-b09d-5c7a47f136d2)
官网出图的风格变化不大 插件出图的变化有点大感觉

**Comment by CikeyQi** [comment]
使用参考图片作图(Vibe Transfer)和图生图(Img2Img)是完全不一样的功能，具体请参考novelai官方公告中Vibe Transfer的使用方法

**Comment by CikeyQi** [comment]
需要Img2Img请使用 `以图画图` 命令，直接 `绘画` 并附带图片将会使用Vibe Transfer模式作图

**Comment by luluxiaoyu** [comment]
好的 谢谢！
