### ISSUE TITLE
绘画出错

### ISSUE THREAD

**Issue by caozhaofeng** [CikeyQi/nai-plugin#8]
Axios Error: connect ETIMEDOUT 31.13.76.99:443
请求帮助
![J6PQCOEZZY@AOSBO(YV_)`H](https://github.com/CikeyQi/nai-plugin/assets/136556424/11e35dc0-a1f0-40b5-a40f-0de181b3ae2c)

**Comment by CikeyQi** [comment]
因为你的服务器是国内的，无法直接访问novelai官网，请配置代理 / 配置反向代理 / 代理软件开启TUN模式才可以正常使用

**Comment by caozhaofeng** [comment]
谢谢，已经解决；我没看到之前已经有人提出这个问题，打扰了
