### ISSUE TITLE
能否直接发送原图

### ISSUE THREAD

**Issue by caozhaofeng** [CikeyQi/nai-plugin#9]
这个插件似乎是直接发送图片，不能发送原图。清晰度被腾讯压缩严重

**Comment by CikeyQi** [comment]
按理来说发送的就是原图，是可以通过解析器解析出tag的

**Comment by caozhaofeng** [comment]
> 按理来说发送的就是原图，是可以通过解析器解析出tag的

发的不是原图文件，直接发出来的图片被压缩，压缩后tag参数全无

**Comment by CikeyQi** [comment]
> > 按理来说发送的就是原图，是可以通过解析器解析出tag的
> 
> 发的不是原图文件，直接发出来的图片被压缩，压缩后tag参数全无

你使用的适配器是？

**Comment by caozhaofeng** [comment]
> > > 按理来说发送的就是原图，是可以通过解析器解析出tag的
> > 
> > 
> > 发的不是原图文件，直接发出来的图片被压缩，压缩后tag参数全无
> 
> 你使用的适配器是？

emmmm，这是适配器你是指？用的是喵版 Miao-Yunzai，登陆端口为aPad

**Comment by CikeyQi** [comment]
好的，晚点我看看

**Comment by CikeyQi** [comment]
已修复

**Comment by Kiana1314** [comment]
能否适配下TRSS-Yunzai的[Telegram](https://gitee.com/TimeRainStarSky/Yunzai-Telegram-Plugin)适配器，发送的图也是压缩过的
![{19B4743D-BF58-43a2-8483-D113B63791FC}](https://github.com/CikeyQi/nai-plugin/assets/107671434/6bb47b04-66a6-4236-8a6c-4c46cbac2166)

**Comment by CikeyQi** [comment]
> 能否适配下TRSS-Yunzai的[Telegram](https://gitee.com/TimeRainStarSky/Yunzai-Telegram-Plugin)适配器，发送的图也是压缩过的 ![{19B4743D-BF58-43a2-8483-D113B63791FC}](https://private-user-images.githubusercontent.com/107671434/304532559-6bb47b04-66a6-4236-8a6c-4c46cbac2166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NTQ3NDMsIm5iZiI6MTcwNzg1NDQ0MywicGF0aCI6Ii8xMDc2NzE0MzQvMzA0NTMyNTU5LTZiYjQ3YjA0LTY2YTYtNDIzNi04YTZjLTRjNDZjYmFjMjE2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QyMDAwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODMxMWY3ZjY2NDBkYmMzZjUwMjFiNjVkZjAwNjBkOGIwYWU5ZTIwMjdmMjU2NmU2YmQ1YzUwZjYyODVmZjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.__99pm1aHLUUpLnHX5u8gAwv49Mj-F-mZG9jaRTVMBE)

Telegram适配器没给其他的图片发送方法，宽度或者高度大于1280自动变成文件发送，否则就以图片发送，参考代码段[Yunzai-Telegram-Plugin](https://gitee.com/TimeRainStarSky/Yunzai-Telegram-Plugin/blob/main/index.js#L52)
